# Сборка датасета для модели сутяжности клиента

Пайплайн вынесен в пакет `querulus.dataset`. Тетрадка только настраивает окружение и вызывает `run_pipeline`.

## Настройка

Флаги: **DATASET** / **FEATURES** / **TRAINING** / **HPO**.

In [1]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
import sys
from pathlib import Path

# Корень репозитория и src/ — как в integration/tests/__init__.py
_here = Path.cwd().resolve()
PROJECT_ROOT = next(
    p for p in (_here, *_here.parents) if (p / "pyproject.toml").exists()
)
SRC = PROJECT_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

In [3]:
import logging

import pandas as pd

# без scientific notation в display (3.45e+04 -> 34545.00)
pd.options.display.float_format = "{:,.2f}".format

from querulus.dataset import run_pipeline
from querulus.dataset.io import setup_notebook_logging

setup_notebook_logging(logging.INFO)

# =============================================================================
# DATASET — откуда берём df
#   DATA_SOURCE: "synthetic" | "final" | "pipeline"
#   LOAD_LEGACY_DATASET — трактовка колонок факта в fin-effect (None=авто)
#   USE_SQL / SAVE_CHECKPOINT — только при pipeline
# =============================================================================
# Smoke HTML-отчёта FS: synthetic → блок B (FS only) →
#   data/processed/train_loop_new/new_selected_features_report_latest.html
# Ячейки EDA / A (triple) можно не запускать.
DATA_SOURCE = "synthetic"  # "synthetic" | "final" | "pipeline"
LOAD_LEGACY_DATASET = None  # None | True | False
USE_SQL = False
SAVE_CHECKPOINT = True

# =============================================================================
# FEATURES — пул и отбор
#   FEATURES_SOURCE: "selected" | "mvp"
#   RUN_FEATURE_SELECT: SHAP RecursiveByShapValues в блоке B
#     (списки → data/processed/train_loop_new/)
#   FEATURE_SELECT_N: единственный N для SHAP (freq и sev) в блоке B
#   RUN_NOISE_CUT: после FS — FE_NOISE_UNIFORM, отсев слабее шума
#   RUN_BACKWARD_ELIM: после noise-cut — срез с конца, best PR-AUC / MAE
#   Только отбор: RUN_TRAIN_LOOP_NEW=True, RUN_FEATURE_SELECT=True, RUN_FIT=False
# =============================================================================
# selected: разные пулы freq/sev → в HTML виден блок «только регрессия»
FEATURES_SOURCE = "selected"  # "selected" | "mvp"
USE_FE_FEATURES = True
# False: при load final/synthetic дропает FE_PERSON_* без пересборки pipeline
INCLUDE_PERSON_FEATURES = True
RUN_FEATURE_SELECT = True
FEATURE_SELECT_N = 5  # мало фич на синтетике (~10/4)
RUN_NOISE_CUT = False  # на синтетике шум может обнулить пул
RUN_BACKWARD_ELIM = False  # на smoke выкл.; на полном прогоне — True

# =============================================================================
# TRAINING — блок B (после feature select)
#   RUN_FIT=False → стоп после отбора фич (без HPO / fit / cal)
# =============================================================================
RUN_TRAIN_LOOP_NEW = True
RUN_CORR_FILTER = False  # быстрее smoke; не режем пул до FS
CORR_FILTER_THRESHOLD = 0.95  # |Pearson r| выше — режем пару (числовые)
RUN_PSI_FILTER = False  # на синтетике PSI сильно режет
PSI_THRESHOLD = 0.5  # числа: >0.25 заметный, >0.5 сильный
L1_THRESHOLD = 0.5  # каты: ~0.2 слабый, ~0.35 заметный, >0.5 сильный
RUN_FIT = False  # False = только feature select (+ HTML-отчёт)
RUN_CALIBRATION = False  # игнорируется при RUN_FIT=False
SEVERITY_VARIANT = "raw"
SEVERITY_SEGMENT_RUB = 50_000
VIEW_STACK = "new"  # "legacy" | "new" | "new_claims"

# =============================================================================
# HPO — Optuna внутри B (только при RUN_FIT=True)
# =============================================================================
RUN_HPO = False
HPO_N_TRIALS = 10

from querulus.training.triple_stack import TARGET_STACKS

STACK_TARGETS = {name: (freq, sev) for name, freq, sev in TARGET_STACKS}
FREQUENCY_TARGET, SEVERITY_TARGET = STACK_TARGETS[VIEW_STACK]
print(
    f"DATA_SOURCE={DATA_SOURCE} FEATURES_SOURCE={FEATURES_SOURCE} "
    f"RUN_FEATURE_SELECT={RUN_FEATURE_SELECT} RUN_NOISE_CUT={RUN_NOISE_CUT} "
    f"RUN_BACKWARD_ELIM={RUN_BACKWARD_ELIM} RUN_FIT={RUN_FIT} "
    f"VIEW_STACK={VIEW_STACK}: {FREQUENCY_TARGET} + {SEVERITY_TARGET}"
)

DATA_SOURCE=synthetic FEATURES_SOURCE=selected RUN_FEATURE_SELECT=True RUN_NOISE_CUT=False RUN_BACKWARD_ELIM=False RUN_FIT=False VIEW_STACK=new: TARGET_FREQ + TARGET_SEV

## Пайплайн

In [4]:
from querulus.dataset.steps.targets import ensure_claims_targets

if DATA_SOURCE in ("synthetic", "final"):
    dataset_path = PROJECT_ROOT / "data" / "processed" / (
        "df_final_3_synthetic.parquet" if DATA_SOURCE == "synthetic" else "df_final_3.parquet"
    )
    if not dataset_path.exists():
        raise FileNotFoundError(
            f"Финальный датасет не найден: {dataset_path}. "
            'Поставьте DATA_SOURCE="pipeline", чтобы собрать его заново.'
        )
    df = pd.read_parquet(dataset_path)
    print(f"DATA_SOURCE={DATA_SOURCE}: load {dataset_path} shape={df.shape}")
else:
    df = run_pipeline(
        use_sql=USE_SQL,
        save_checkpoint=SAVE_CHECKPOINT,
        include_fe_features=USE_FE_FEATURES,
        include_person_features=INCLUDE_PERSON_FEATURES,
    )
    print(f"DATA_SOURCE=pipeline: assembled shape={df.shape}")

df = ensure_claims_targets(df)
from querulus.features.integer_casts import cast_integer_like_columns

# Age/year и 0/1-флаги → Int64 (в т.ч. при load final без пересборки)
df = cast_integer_like_columns(df)
if not USE_FE_FEATURES:
    fe_cols = [c for c in df.columns if str(c).startswith("FE_")]
    if fe_cols:
        df = df.drop(columns=fe_cols)
        print(f"Dropped {len(fe_cols)} FE_* columns (USE_FE_FEATURES=False)")
elif not INCLUDE_PERSON_FEATURES:
    # Быстрый обход без пересборки: убрать FE_PERSON_* из уже собранного parquet
    person_cols = [c for c in df.columns if str(c).startswith("FE_PERSON_")]
    if person_cols:
        df = df.drop(columns=person_cols)
        print(
            f"Dropped {len(person_cols)} FE_PERSON_* columns "
            f"(INCLUDE_PERSON_FEATURES=False, без пересборки)"
        )
FREQUENCY_TARGET, SEVERITY_TARGET = STACK_TARGETS[VIEW_STACK]
print(
    f"VIEW_STACK={VIEW_STACK}: {FREQUENCY_TARGET} + {SEVERITY_TARGET}, columns ok="
    f"{FREQUENCY_TARGET in df.columns and SEVERITY_TARGET in df.columns}"
)

DATA_SOURCE=synthetic: load C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\data\processed\df_final_3_synthetic.parquet shape=(400, 37)
VIEW_STACK=new: TARGET_FREQ + TARGET_SEV, columns ok=True

## Проверка результата

In [5]:
from IPython.display import Markdown, display
from querulus.training.triple_stack import TARGET_STACKS

# stacks-check-v2: только value_counts + sum + describe(sev>0), без хардкодов
for stack_name, freq_col, sev_col in TARGET_STACKS:
    display(Markdown(f"### {stack_name}: `{freq_col}` / `{sev_col}`"))
    if freq_col not in df.columns:
        print(f"нет колонки {freq_col} — пересоберите датасет или ensure_claims_targets")
        continue
    display(df[freq_col].value_counts(dropna=False).rename("n").to_frame())
    if sev_col not in df.columns:
        print(f"нет колонки {sev_col}")
        continue
    print(f"sum({sev_col}) = {float(df[sev_col].sum()):,.2f}")
    pos = df.loc[df[sev_col] > 0, sev_col]
    if pos.empty:
        print(f"{sev_col}: нет строк > 0")
    else:
        display(pos.describe().to_frame("sev>0"))

### legacy: `TARGET_2` / `TARGET_3_SEV`

            n
TARGET_2
0         280
1         120

sum(TARGET_3_SEV) = 5,473,611.43

           sev>0
count     113.00
mean   48,439.04
std    48,132.93
min     4,657.64
25%    18,399.38
50%    34,011.26
75%    56,389.58
max   322,984.82

### new: `TARGET_FREQ` / `TARGET_SEV`

               n
TARGET_FREQ
0            287
1            113

sum(TARGET_SEV) = 5,511,374.20

           sev>0
count     113.00
mean   48,773.22
std    47,673.20
min     4,682.40
25%    20,141.14
50%    32,860.64
75%    58,235.17
max   317,086.14

### new_claims: `TARGET_FREQ_CLAIMS` / `TARGET_SEV_CLAIMS`

                      n
TARGET_FREQ_CLAIMS
0                   316
1                    84

sum(TARGET_SEV_CLAIMS) = 3,906,876.98

           sev>0
count      84.00
mean   46,510.44
std    50,506.92
min     4,951.17
25%    17,264.19
50%    29,766.11
75%    52,659.08
max   304,807.54

In [6]:
# Проверка: freq==0 при sev>0 (для new и new_claims)
for freq_col, sev_col in (("TARGET_FREQ", "TARGET_SEV"), ("TARGET_FREQ_CLAIMS", "TARGET_SEV_CLAIMS")):
    if freq_col not in df.columns or sev_col not in df.columns:
        print(f"skip {freq_col}/{sev_col}: колонок нет")
        continue
    mask = (df[freq_col].fillna(0) == 0) & (df[sev_col].fillna(0) > 0)
    print(f"{freq_col}==0 & {sev_col}>0: {int(mask.sum())} / {len(df)}")
    cols = [c for c in ["INCIDENT_NUMBER", "LOSS_NUMBER", freq_col, sev_col] if c in df.columns]
    display(df.loc[mask, cols].head(20))

TARGET_FREQ==0 & TARGET_SEV>0: 0 / 400

Empty DataFrame
Columns: [INCIDENT_NUMBER, TARGET_FREQ, TARGET_SEV]
Index: []

TARGET_FREQ_CLAIMS==0 & TARGET_SEV_CLAIMS>0: 0 / 400

Empty DataFrame
Columns: [INCIDENT_NUMBER, TARGET_FREQ_CLAIMS, TARGET_SEV_CLAIMS]
Index: []

## Сверка таргетов

1. **Litigant (old) vs Querulus:** `TARGET_2`, `TARGET_3_SEV` + топ-20.
2. **На Querulus — 6 таргетов:** legacy / new / new_claims (пары old↔new, old↔claims, new↔claims) + топ-20.

In [7]:
from querulus.training.target_compare import (
    default_litigant_dataset_path,
    run_target_comparison_suite,
)

# litigant_path = Path("/home/jovyan/old_home/Litigant/data/processed/df_final_3.parquet")
suite = run_target_comparison_suite(
    df,
    litigant_path=default_litigant_dataset_path(),
    top_n=20,
)

if suite.litigant is not None:
    print("=== 1. Litigant vs Querulus (TARGET_2, TARGET_3_SEV) ===")
    display(suite.litigant.report)
    print("=== 2. Топ-20: классификация TARGET_2 (old vs new) ===")
    display(suite.litigant.top_classification)
    print("=== 2. Топ-20: регрессия TARGET_3_SEV (old vs new) ===")
    display(suite.litigant.top_regression)
else:
    print(f"Litigant parquet не найден — блок 1–2 пропущен ({default_litigant_dataset_path()})")

print("=== 3. Статистика: legacy / new / new_claims (6 таргетов) ===")
display(suite.old_vs_new.report)
print("=== 4. Топ-20: классификация ===")
display(suite.old_vs_new.top_classification)
print("=== 4. Топ-20: регрессия ===")
display(suite.old_vs_new.top_regression)

Litigant parquet не найден — блок 1–2 пропущен (C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\data\processed\df_final_3_litigant.parquet)
=== 3. Статистика: legacy / new / new_claims (6 таргетов) ===

,pair,col_reference,col_candidate,kind,common_n,exact_match_n,exact_match_pct,mismatch_n,mismatch_pct,pct_match_at_threshold
0,TARGET_2 vs TARGET_FREQ,TARGET_2,TARGET_FREQ,binary,400,393,98.25,7,1.75,NaN
1,TARGET_3_SEV vs TARGET_SEV,TARGET_3_SEV,TARGET_SEV,float,400,287,71.75,113,28.25,73.50
2,TARGET_2 vs TARGET_FREQ_CLAIMS,TARGET_2,TARGET_FREQ_CLAIMS,binary,400,364,91.00,36,9.00,NaN
3,TARGET_3_SEV vs TARGET_SEV_CLAIMS,TARGET_3_SEV,TARGET_SEV_CLAIMS,float,400,287,71.75,113,28.25,72.25
4,TARGET_FREQ vs TARGET_FREQ_CLAIMS,TARGET_FREQ,TARGET_FREQ_CLAIMS,binary,400,371,92.75,29,7.25,NaN
5,TARGET_SEV vs TARGET_SEV_CLAIMS,TARGET_SEV,TARGET_SEV_CLAIMS,float,400,287,71.75,113,28.25,72.25

=== 4. Топ-20: классификация ===

,INCIDENT_NUMBER,Сумма_выплат_по_претензиям,Сумма_взыскано_по_ФУ,Суммы_взыскано_по_иску,TARGET_2,TARGET_FREQ
0,SYN-000100,0.00,0.00,0.00,1,0
1,SYN-000118,0.00,0.00,0.00,1,0
2,SYN-000141,0.00,0.00,0.00,1,0
3,SYN-000220,0.00,0.00,0.00,1,0
4,SYN-000227,0.00,0.00,0.00,1,0
5,SYN-000304,0.00,0.00,0.00,1,0
6,SYN-000319,0.00,0.00,0.00,1,0

=== 4. Топ-20: регрессия ===

   INCIDENT_NUMBER  TARGET_3_SEV  TARGET_SEV
0       SYN-000065    178,981.74  207,893.71
1       SYN-000008    224,958.64  198,332.87
2       SYN-000261    192,037.71  173,126.65
3       SYN-000053    125,366.98  142,813.73
4       SYN-000254    125,498.94  136,929.64
5       SYN-000194    125,882.32  115,305.17
6       SYN-000272     72,967.77   82,755.70
7       SYN-000109     80,069.64   71,124.10
8       SYN-000309     95,690.14  104,632.06
9       SYN-000318     97,352.16   88,604.57
10      SYN-000140     56,389.58   65,048.39
11      SYN-000337     75,812.51   84,060.69
12      SYN-000216     44,089.92   50,643.95
13      SYN-000101     44,109.98   50,490.86
14      SYN-000163     78,731.50   85,091.60
15      SYN-000081    108,144.50  101,787.34
16      SYN-000080     48,205.86   42,225.80
17      SYN-000054    322,984.82  317,086.14
18      SYN-000208     39,044.26   44,867.51
19      SYN-000221     92,541.30   86,852.04

## EDA признаков

`research_continous` / `research_feature` по MVP-признакам (до обучения, как в `model_learn.py`).

In [8]:
from querulus.training.config import TrainingConfig
from querulus.training.plots import run_mvp_frequency_eda

EDA_CONFIG = TrainingConfig(
    frequency_target=FREQUENCY_TARGET,
    severity_target=SEVERITY_TARGET,
    features_source=FEATURES_SOURCE,
)
if "expos" not in df.columns:
    df["expos"] = 1

run_mvp_frequency_eda(df, EDA_CONFIG)

100%|██████████| 38/38 [00:00<00:00, 2533.32it/s]
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

=== Frequency MVP EDA (numeric) ===
VICTIM_VEHICLE_AGE nulls: 0.0 %
VICTIM_MAX_WEIGHT nulls: 0.0 %
GUILTY_CAPACITY_ENGINE nulls: 0.0 %
APPLICANT_AGE nulls: 0.0 %
EVENT_YEAR nulls: 0.0 %
APPLY_DELAY nulls: 0.0 %
PREMIUM_COUNT_ALL nulls: 0.0 %
FE_VALUE_BEFORE_WITHOUT_REAL_2020 nulls: 0.0 %
FE_VALUE_BEFORE_WITH_REAL_2020 nulls: 0.0 %

C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

FE_PREMIUM_SUM_ALL_REAL_2020 nulls: 0.0 %
FE_VALUE_BEFORE_DIFF nulls: 0.0 %
FE_VALUE_BEFORE_RATIO nulls: 0.0 %

=== Frequency MVP EDA (binary) ===
EVENT_CREATED_BY_GIBDD_FLAG nulls: 0.0 %
EVENT_CREATED_BY_GIBDD_FLAG nunique: 2

=== Frequency MVP EDA (categorical) ===
FILIAL nulls: 0.0 %
FILIAL nunique: 4
VICTIM_VEHICLE_CATEGORY nulls: 0.0 %
VICTIM_VEHICLE_CATEGORY nunique: 3
APPLICANT_FORM nulls: 0.0 %
APPLICANT_FORM nunique: 3
RECIEVE_METHOD nulls: 0.0 %
RECIEVE_METHOD nunique: 3
LOSS_UNIT_ZONE nulls: 0.0 %
LOSS_UNIT_ZONE nunique: 4
VICTIM_VEHICLE_COUNTRY nulls: 0.0 %
VICTIM_VEHICLE_COUNTRY nunique: 3

C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\research_eda.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## A. Research: сравнение трёх стеков

Быстрое сравнение `legacy` / `new` / `new_claims` **без** corr-filter / HPO / калибровки.
Правильный train-loop кандидата `new` — в **блоке B** ниже (`RUN_TRAIN_LOOP_NEW`).

Признаки: `FEATURES_SOURCE`. Отбор фич — в блоке B (`RUN_FEATURE_SELECT`), не здесь.
`severity_range=None`: severity на `target > 0`.

In [9]:
import importlib

importlib.invalidate_caches()

from IPython.display import Markdown, display

from querulus.training.config import TrainingConfig
from querulus.training.pipeline import format_features_table, format_training_summary
from querulus.training.triple_stack import run_triple_stack

# Отбор фич (N) — только FEATURE_SELECT_N → TrainLoopFlags в блоке B.
TRAINING_CONFIG = TrainingConfig(
    features_source=FEATURES_SOURCE,
    frequency_select_features=False,
    severity_select_features=False,
    frequency_calibration_enabled=True,
    severity_range=None,
)
triple = run_triple_stack(
    df,
    TRAINING_CONFIG,
    split="test",
    loaded_from_checkpoint=(DATA_SOURCE != "pipeline"),
    legacy_dataset=LOAD_LEGACY_DATASET,
    run_fin_effect=True,
)

# Для диагностики / графиков — выбранный VIEW_STACK
training = triple.trainings[VIEW_STACK]
FREQUENCY_TARGET, SEVERITY_TARGET = STACK_TARGETS[VIEW_STACK]

display(Markdown("### Metrics summary (legacy / new / new_claims)"))
display(triple.metrics_summary)

display(Markdown(f"### Training summary ({VIEW_STACK})"))
display(format_training_summary(training.summary))

display(Markdown(f"### Frequency features ({VIEW_STACK})"))
display(format_features_table(training.frequency_features, training.frequency_categorical_features))

display(Markdown(f"### Severity features ({VIEW_STACK})"))
display(format_features_table(training.severity_features, training.severity_categorical_features))

display(Markdown(f"### Frequency importance ({VIEW_STACK})"))
display(training.frequency_importance.head(30))
display(Markdown(f"### Severity importance ({VIEW_STACK})"))
display(training.severity_importance.head(30))

100%|██████████| 38/38 [00:00<00:00, 2922.70it/s]

Обучение стека legacy: TARGET_2 + TARGET_3_SEV ...

Learning rate set to 0.035453
0:	learn: 0.6890974	test: 0.6929901	best: 0.6929901 (0)	total: 168ms	remaining: 1m 2s
250:	learn: 0.2438570	test: 0.6977600	best: 0.6737897 (75)	total: 5.6s	remaining: 2.77s
374:	learn: 0.1395968	test: 0.7347358	best: 0.6737897 (75)	total: 8.11s	remaining: 0us

bestTest = 0.6737897212
bestIteration = 75

Shrink model to first 76 iterations.
Learning rate set to 0.140607
0:	learn: 51943.4871370	test: 28864.8059949	best: 28864.8059949 (0)	total: 17.1ms	remaining: 1.69s

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\calibration.py:330: FutureWarning: The `cv='prefit'` option is deprecated in 1.6 and will be removed in 1.8. You can use CalibratedClassifierCV(FrozenEstimator(estimator)) instead.
  warnings.warn(

99:	learn: 21697.2644882	test: 33444.3232539	best: 28754.5233769 (14)	total: 1.54s	remaining: 0us

bestTest = 28754.52338
bestIteration = 14

Shrink model to first 15 iterations.

C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\gini.py:54: FutureWarning: The provided callable <function mean at 0x000001D52DD12200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pred_order = pd.DataFrame(arr).groupby([1])[0].transform(np.mean)[arr[:,1].argsort()].values[::-1]
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\gini.py:54: FutureWarning: The provided callable <function mean at 0x000001D52DD12200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pred_order = pd.DataFrame(arr).groupby([1])[0].transform(np.mean)[arr[:,1].argsort()].values[::-1]
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Обучение стека new: TARGET_FREQ + TARGET_SEV ...
Learning rate set to 0.035453
0:	learn: 0.6880726	test: 0.6925193	best: 0.6925193 (0)	total: 17.9ms	remaining: 6.71s

250:	learn: 0.2502512	test: 0.6987294	best: 0.6714371 (116)	total: 4.5s	remaining: 2.22s
374:	learn: 0.1469013	test: 0.7454396	best: 0.6714371 (116)	total: 6.94s	remaining: 0us

bestTest = 0.6714371291
bestIteration = 116

Shrink model to first 117 iterations.
Learning rate set to 0.140607
0:	learn: 51418.2413129	test: 29248.4814314	best: 29248.4814314 (0)	total: 14ms	remaining: 1.39s

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\calibration.py:330: FutureWarning: The `cv='prefit'` option is deprecated in 1.6 and will be removed in 1.8. You can use CalibratedClassifierCV(FrozenEstimator(estimator)) instead.
  warnings.warn(

99:	learn: 20260.8171515	test: 38077.7483687	best: 29170.3587083 (1)	total: 1.59s	remaining: 0us

bestTest = 29170.35871
bestIteration = 1

Shrink model to first 2 iterations.

C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\gini.py:54: FutureWarning: The provided callable <function mean at 0x000001D52DD12200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pred_order = pd.DataFrame(arr).groupby([1])[0].transform(np.mean)[arr[:,1].argsort()].values[::-1]
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\gini.py:54: FutureWarning: The provided callable <function mean at 0x000001D52DD12200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pred_order = pd.DataFrame(arr).groupby([1])[0].transform(np.mean)[arr[:,1].argsort()].values[::-1]
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Обучение стека new_claims: TARGET_FREQ_CLAIMS + TARGET_SEV_CLAIMS ...
Learning rate set to 0.035453
0:	learn: 0.6855820	test: 0.6904231	best: 0.6904231 (0)	total: 21.6ms	remaining: 8.07s
250:	learn: 0.2302992	test: 0.6969005	best: 0.6681985 (68)	total: 4.26s	remaining: 2.1s
374:	learn: 0.1356357	test: 0.7549692	best: 0.6681985 (68)	total: 6.93s	remaining: 0us

bestTest = 0.6681984927
bestIteration = 68

Shrink model to first 69 iterations.
Learning rate set to 0.134061
0:	learn: 55498.6275871	test: 27254.9948887	best: 27254.9948887 (0)	total: 10.7ms	remaining: 1.06s

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\calibration.py:330: FutureWarning: The `cv='prefit'` option is deprecated in 1.6 and will be removed in 1.8. You can use CalibratedClassifierCV(FrozenEstimator(estimator)) instead.
  warnings.warn(

99:	learn: 20596.1997389	test: 36273.8142564	best: 27254.9948887 (0)	total: 1.7s	remaining: 0us

bestTest = 27254.99489
bestIteration = 0

Shrink model to first 1 iterations.

C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\gini.py:54: FutureWarning: The provided callable <function mean at 0x000001D52DD12200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pred_order = pd.DataFrame(arr).groupby([1])[0].transform(np.mean)[arr[:,1].argsort()].values[::-1]
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\gini.py:54: FutureWarning: The provided callable <function mean at 0x000001D52DD12200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pred_order = pd.DataFrame(arr).groupby([1])[0].transform(np.mean)[arr[:,1].argsort()].values[::-1]
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

### Metrics summary (legacy / new / new_claims)

,task,metric,split,legacy,new,new_claims
0,frequency,best_threshold,test,0.49,0.48,0.50
1,frequency,best_threshold_metric,test,f1_score,f1_score,f1_score
2,frequency,ece,test,0.02,0.01,0.01
3,frequency,f1_score,test,0.45,0.41,0.46
4,frequency,gini,test,0.24,0.16,0.28
5,frequency,mcc,test,0.18,0.18,0.33
6,frequency,pr_auc,test,0.44,0.37,0.48
7,frequency,precision_score,test,0.33,0.34,0.42
8,frequency,recall_score,test,0.68,0.52,0.50
9,frequency,roc_auc,test,0.62,0.58,0.64
10,frequency,sensitivity,test,0.68,0.52,0.50
11,frequency,shift,test,2.03,1.52,1.18
12,frequency,specificity,test,0.53,0.68,0.85
13,frequency,youden_index,test,0.21,0.20,0.35
14,frequency,best_threshold,train,0.48,0.51,0.53
15,frequency,best_threshold_metric,train,f1_score,f1_score,f1_score
16,frequency,ece,train,0.04,0.01,0.00
17,frequency,f1_score,train,0.65,0.68,0.74
18,frequency,gini,train,0.62,0.72,0.82
19,frequency,mcc,train,0.46,0.55,0.66
20,frequency,pr_auc,train,0.63,0.74,0.79
21,frequency,precision_score,train,0.53,0.69,0.73
22,frequency,recall_score,train,0.85,0.68,0.74
23,frequency,roc_auc,train,0.81,0.86,0.91
24,frequency,sensitivity,train,0.85,0.68,0.74
25,frequency,shift,train,1.62,0.99,1.02
26,frequency,specificity,train,0.64,0.87,0.92
27,frequency,youden_index,train,0.50,0.55,0.66
28,severity,bias,test,"-5,982.09","-7,347.28","-14,677.49"
29,severity,gini,test,0.08,0.19,-0.13
30,severity,mae,test,"24,977.85","25,137.73","24,596.51"
31,severity,mape,test,1.17,1.20,1.47
32,severity,max_error,test,"49,308.34","54,849.99","44,494.40"
33,severity,median_error,test,"-17,300.80","-16,471.76","-18,936.85"
34,severity,mpe,test,-0.95,-1.01,-1.34
35,severity,mse,test,"826,822,636.05","850,909,831.71","742,834,754.32"
36,severity,r2,test,-0.06,-0.04,-0.47
37,severity,rmse,test,"28,754.52","29,170.36","27,255.00"
38,severity,shift,test,1.14,1.17,1.42
39,severity,bias,train,617.07,-314.79,33.48
40,severity,gini,train,0.53,0.44,0.41
41,severity,mae,train,"34,073.14","35,415.22","38,568.98"
42,severity,mape,train,1.37,1.42,1.55
43,severity,max_error,train,"227,031.39","258,089.25","251,910.88"
44,severity,median_error,train,"-17,381.84","-19,649.04","-19,276.28"
45,severity,mpe,train,-1.10,-1.17,-1.30
46,severity,mse,train,"2,338,119,428.25","2,627,896,654.18","3,079,441,512.88"
47,severity,r2,train,0.17,0.04,0.03
48,severity,rmse,train,"48,354.10","51,263.01","55,492.72"
49,severity,shift,train,0.99,1.01,1.00

### Training summary (new)

,model,parameter,value
0,mvp,mvp_features,19
1,mvp,mvp_categorical_features,7
2,mvp,date_column,LOSS_DATE_TIME
3,frequency,target,TARGET_FREQ
4,frequency,train_period,2022-01-01 .. 2024-05-31
5,frequency,test_period,2024-06-01 .. 2025-06-01
6,frequency,target_filter,—
7,frequency,train_rows,280
8,frequency,test_rows,120
9,frequency,train_share_pct,70.00
10,frequency,test_share_pct,30.00
11,frequency,train_target_mean,0.300000
12,frequency,test_target_mean,0.241667
13,frequency,features_count,10
14,frequency,features,"EVENT_CREATED_BY_GIBDD_FLAG, FILIAL, VICTIM_VE..."
15,frequency,cat_features_count,5
16,frequency,cat_features,"FILIAL, VICTIM_VEHICLE_CATEGORY, APPLICANT_FOR..."
17,frequency,iterations,375
18,frequency,random_state,0
19,frequency,auto_class_weights,Balanced
20,frequency,verbose,250
21,severity,target,TARGET_SEV
22,severity,train_period,2022-01-01 .. 2024-05-31
23,severity,test_period,2024-06-01 .. 2025-06-01
24,severity,target_filter,TARGET_SEV > 0
25,severity,train_rows,84
26,severity,test_rows,29
27,severity,train_share_pct,74.34
28,severity,test_share_pct,25.66
29,severity,train_target_mean,50592.201879
30,severity,test_target_mean,43504.456712
31,severity,features_count,4
32,severity,features,"LOSS_UNIT_ZONE, VICTIM_VEHICLE_COUNTRY, APPLY_..."
33,severity,cat_features_count,2
34,severity,cat_features,"LOSS_UNIT_ZONE, VICTIM_VEHICLE_COUNTRY"
35,severity,iterations,100
36,severity,random_state,0
37,severity,verbose,250

### Frequency features (new)

                       feature         type
0  EVENT_CREATED_BY_GIBDD_FLAG  categorical
1                       FILIAL  categorical
2      VICTIM_VEHICLE_CATEGORY  categorical
3               APPLICANT_FORM  categorical
4               RECIEVE_METHOD  categorical
5           VICTIM_VEHICLE_AGE      numeric
6            VICTIM_MAX_WEIGHT      numeric
7       GUILTY_CAPACITY_ENGINE      numeric
8                APPLICANT_AGE      numeric
9                   EVENT_YEAR      numeric

### Severity features (new)

                             feature         type
0                     LOSS_UNIT_ZONE  categorical
1             VICTIM_VEHICLE_COUNTRY  categorical
2                        APPLY_DELAY      numeric
3  FE_VALUE_BEFORE_WITHOUT_REAL_2020      numeric

### Frequency importance (new)

                       feature  importance
0               RECIEVE_METHOD       21.04
1               APPLICANT_FORM       12.12
2                APPLICANT_AGE       11.95
3                       FILIAL       11.82
4      VICTIM_VEHICLE_CATEGORY       11.48
5           VICTIM_VEHICLE_AGE        7.88
6       GUILTY_CAPACITY_ENGINE        7.48
7            VICTIM_MAX_WEIGHT        7.13
8                   EVENT_YEAR        5.26
9  EVENT_CREATED_BY_GIBDD_FLAG        3.83

### Severity importance (new)

                             feature  importance
0                        APPLY_DELAY       66.22
1  FE_VALUE_BEFORE_WITHOUT_REAL_2020       23.20
2                     LOSS_UNIT_ZONE       10.58
3             VICTIM_VEHICLE_COUNTRY        0.00

## Диагностика модели

Распределение вероятностей классификации и ModelDiagnostics (после обучения).

In [10]:
from querulus.training.plots import run_model_diagnostics_visualizations

# Диагностика стека VIEW_STACK (training = triple.trainings[VIEW_STACK])
print(f"diagnostics for VIEW_STACK={VIEW_STACK}: {FREQUENCY_TARGET} + {SEVERITY_TARGET}")
run_model_diagnostics_visualizations(df, training, TRAINING_CONFIG)

diagnostics for VIEW_STACK=new: TARGET_FREQ + TARGET_SEV

=== Frequency probability diagnostics ===

C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\plots.py:63: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\plots.py:65: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig, axes = plt.subplots(1, 2, figsize=(14, 5))
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\plots.py:113: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

==================================================
СТАТИСТИКА РАЗДЕЛИМОСТИ КЛАССОВ
==================================================

Train:
  Класс 0: mean=0.417, std=0.081, median=0.408
  Класс 1: mean=0.542, std=0.076, median=0.541
  Разрыв mean: 0.125

Test:
  Класс 0: mean=0.439, std=0.081, median=0.443
  Класс 1: mean=0.466, std=0.089, median=0.483
  Разрыв mean: 0.027

Разница в разрыве (test - train): -0.098

==================================================
СВОДКА ПО МЕТРИКАМ
==================================================
Average Precision: Train=0.741, Test=0.369, Δ=-0.372
ROC-AUC:           Train=0.861, Test=0.579, Δ=-0.282

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\utils\_plotting.py:175: FutureWarning: `**kwargs` is deprecated and will be removed in 1.9. Pass all matplotlib arguments to `curve_kwargs` as a dictionary instead.
  warnings.warn(
c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\utils\_plotting.py:175: FutureWarning: `**kwargs` is deprecated and will be removed in 1.9. Pass all matplotlib arguments to `curve_kwargs` as a dictionary instead.
  warnings.warn(
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\training\plots.py:148: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\modeldiagnostics.py:496: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\modeldiagnostics.py:496: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

=== Таблица аномальных точек (Cook's D > 0.0476), топ-10 ===
 Index  Leverage   Residual  Cook's D
    15      0.15 258,089.25      2.57
     4      0.05 143,419.81      0.19
    20      0.03 154,401.75      0.12
    79      0.04 118,812.12      0.10

=== Таблица аномальных точек (Cook's D > 0.1379), топ-10 ===
 Index  Leverage   Residual  Cook's D
    17      0.48 -20,267.42      0.43

C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\modeldiagnostics.py:420: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\modeldiagnostics.py:420: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Финансовый эффект (три стека)

Сводная таблица: threshold / fact / model / net по `legacy`, `new`, `new_claims`.
Детальная сводка квадрантов — для `VIEW_STACK`.

In [11]:
from querulus.fin_effect import (
    create_summary_table,
    export_analytics_excel,
    export_summary_excel,
    print_best_threshold_report,
    resolve_fin_effect_config,
)

display(Markdown("### Fin-effect summary (3 stacks)"))
display(triple.fin_effect_summary)

FIN_EFFECT_CONFIG = resolve_fin_effect_config(
    df,
    frequency_target=FREQUENCY_TARGET,
    severity_target=SEVERITY_TARGET,
    loaded_from_checkpoint=(DATA_SOURCE != "pipeline"),
    legacy_dataset=LOAD_LEGACY_DATASET,
)
fin_effect = triple.fin_effects[VIEW_STACK]
print(f"VIEW_STACK={VIEW_STACK} fact_mode={FIN_EFFECT_CONFIG.fact_mode}")
print_best_threshold_report(fin_effect)

FIN_EFFECT_DIR = PROJECT_ROOT / "data" / "processed" / "fin_effect"
FIN_EFFECT_DIR.mkdir(parents=True, exist_ok=True)

summary_table = create_summary_table(fin_effect.frame, FIN_EFFECT_CONFIG)
display(summary_table.style.format("{:,.0f}", subset=summary_table.columns[3:]))

export_summary_excel(summary_table, FIN_EFFECT_DIR / f"summary_table_{VIEW_STACK}.xlsx")
export_analytics_excel(
    fin_effect.frame, FIN_EFFECT_DIR / f"Аналитика_{VIEW_STACK}.xlsx", config=FIN_EFFECT_CONFIG
)

triple.fin_effect_summary.to_excel(FIN_EFFECT_DIR / "fin_effect_triple_summary.xlsx", index=False)
triple.metrics_summary.to_excel(FIN_EFFECT_DIR / "metrics_triple_summary.xlsx", index=False)
print(f"Экспорт: {FIN_EFFECT_DIR}")

### Fin-effect summary (3 stacks)

,stack,frequency_target,severity_target,fact_mode,fact_amount_column,best_threshold,fact_effect,model_effect,net_effect
0,legacy,TARGET_2,TARGET_3_SEV,legacy_psr,legacy_psr,0.90,"-1,185,919.58","-1,185,919.58",0.00
1,new,TARGET_FREQ,TARGET_SEV,icnl,TARGET_FREQ_AMOUNT,0.80,"-1,325,240.58","-1,325,240.58",0.00
2,new_claims,TARGET_FREQ_CLAIMS,TARGET_SEV_CLAIMS,icnl,TARGET_FREQ_CLAIMS_AMOUNT,0.95,"-763,137.83","-763,137.83",0.00

VIEW_STACK=new fact_mode=icnl

======================================================================
ОПТИМАЛЬНЫЙ ПОРОГ КЛАССИФИКАЦИИ
======================================================================
Порог вероятности              : 0.80
Фин. эффект факт (baseline)    : -1,325,240.58 ₽
Фин. эффект модели             : -1,325,240.58 ₽
Чистый финансовый эффект (Δ)   : 0.00 ₽

Сравнение стратегий порога:
  best_net_effect      threshold=0.80 net_effect=0 F1=0.129 PR-AUC=0.338
  pr_auc               threshold=0.27 net_effect=-1,571,418 F1=0.394 PR-AUC=0.338

Экспорт: C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\data\processed\fin_effect

In [12]:
from querulus.fin_effect import (
    plot_confusion_matrix,
    plot_cost_confusion_heatmaps,
    plot_positive_cases_by_month,
    plot_precision_recall_vs_threshold,
    plot_severity_fact_vs_pred_binned,
    plot_target_monthly_share,
)

split = training.frequency_split
frame = fin_effect.frame
y_test = split.y_test.loc[frame.index]
x_test = split.x_test.loc[frame.index, training.frequency_features]

business_threshold = fin_effect.best_threshold
plot_confusion_matrix(
    frame[FIN_EFFECT_CONFIG.frequency_target_column],
    frame["pred_freq"],
    title=f"Confusion Matrix {FREQUENCY_TARGET} (threshold={business_threshold:.2f})",
)
plot_precision_recall_vs_threshold(training.frequency_model, x_test, y_test)
plot_cost_confusion_heatmaps(frame, y_test, frame["pred_freq"])
plot_severity_fact_vs_pred_binned(
    frame,
    frame[SEVERITY_TARGET],
    frame["pred_sev"],
    mask_actual_claim=(y_test == 1),
    config=FIN_EFFECT_CONFIG,
)
plot_target_monthly_share(df, config=FIN_EFFECT_CONFIG)
plot_positive_cases_by_month(df, config=FIN_EFFECT_CONFIG)

C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\fin_effect\plots.py:41: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\fin_effect\plots.py:152: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\fin_effect\plots.py:373: UserWarning:

FigureCanvasAgg is non-interactive, and thus cannot be shown

C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\src\querulus\fin_effect\plots.py:403: UserWarning:

FigureCanvasAgg is non-interactive, and thus cannot be shown

### Severity zoo → выбор для блока B

Сравнение вариантов severity **до** train-loop. После таблиц задайте `SEVERITY_VARIANT`:
`raw` | `log1p` | `weighted_sqrt` | `weighted_linear` | `raw_le50` | `log1p_le50` | `raw_gt50` | `log1p_gt50`.

Сегментные `*_le50` / `*_gt50` — только на срезе `VALUE_BEFORE_WITH` ≤ / > порога.

In [13]:
from querulus.training import run_severity_zoo_compare
from querulus.training.severity_variant import SEVERITY_VARIANT_NAMES

sev_zoo = run_severity_zoo_compare(
    df,
    training,
    FIN_EFFECT_CONFIG,
    TRAINING_CONFIG,
    split="test",
    value_column="VALUE_BEFORE_WITH",
    value_threshold=SEVERITY_SEGMENT_RUB,
)

display(
    Markdown(
        f"### Severity metrics summary ({VIEW_STACK})  \n"
        f"Квантили бьются по **`{sev_zoo.bin_axis}`** (true severity).  \n"
        f"Сегменты: `{sev_zoo.value_column}` ≤ / > {sev_zoo.value_threshold:,.0f}."
    )
)
display(sev_zoo.metrics_summary)

display(Markdown("### Severity quantile summary (все варианты)"))
display(sev_zoo.quantile_summary)

display(Markdown("### Fin-effect summary (все варианты, один threshold)"))
display(sev_zoo.fin_effect_summary)

display(Markdown("### Fin-effect penalty summary (pred < fact)"))
display(sev_zoo.penalty_summary)

ZOO_DIR = PROJECT_ROOT / "data" / "processed" / "fin_effect"
ZOO_DIR.mkdir(parents=True, exist_ok=True)
sev_zoo.metrics_summary.to_excel(ZOO_DIR / f"severity_zoo_metrics_{VIEW_STACK}.xlsx", index=False)
sev_zoo.quantile_summary.to_excel(ZOO_DIR / f"severity_zoo_quantiles_{VIEW_STACK}.xlsx", index=False)
sev_zoo.fin_effect_summary.to_excel(ZOO_DIR / f"severity_zoo_fin_effect_{VIEW_STACK}.xlsx", index=False)
sev_zoo.penalty_summary.to_excel(ZOO_DIR / f"severity_zoo_penalty_{VIEW_STACK}.xlsx", index=False)
print(f"Severity zoo export: {ZOO_DIR}")

print("Допустимые SEVERITY_VARIANT:", SEVERITY_VARIANT_NAMES)
print("Сейчас SEVERITY_VARIANT =", SEVERITY_VARIANT)
# SEVERITY_VARIANT = "log1p"  # ← раскомментируйте после выбора по таблицам

Learning rate set to 0.140607
0:	learn: 0.8869997	test: 0.7552036	best: 0.7552036 (0)	total: 4.59ms	remaining: 455ms
99:	learn: 0.3663609	test: 0.8478916	best: 0.7552036 (0)	total: 1.76s	remaining: 0us

bestTest = 0.7552036398
bestIteration = 0

Shrink model to first 1 iterations.
Learning rate set to 0.140607
0:	learn: 68033.6334558	test: 41364.1389398	best: 41364.1389398 (0)	total: 5.42ms	remaining: 537ms
99:	learn: 22365.1256240	test: 38828.9290856	best: 38239.9568501 (83)	total: 1.96s	remaining: 0us

bestTest = 38239.95685
bestIteration = 83

Shrink model to first 84 iterations.
Learning rate set to 0.140607
0:	learn: 80711.3921915	test: 65463.9097965	best: 65463.9097965 (0)	total: 4.24ms	remaining: 420ms
99:	learn: 29191.3121306	test: 48992.5147142	best: 48992.5147142 (99)	total: 1.35s	remaining: 0us

bestTest = 48992.51471
bestIteration = 99

Learning rate set to 0.12465
0:	learn: 44045.1053386	test: 30460.3299502	best: 30460.3299502 (0)	total: 12.4ms	remaining: 1.23s
99:	learn: 12303.6579626	test: 35819.8550040	best: 30416.8939778 (2)	total: 1.72s	remaining: 0us

bestTest = 30416.89398
bestIteration = 2

Shrink model to first 3 iterations.
Learning rate set to 0.12465
0:	learn: 0.8674315	test: 0.7587879	best: 0.7587879 (0)	total: 15.3ms	remaining: 1.51s
99:	learn: 0.2616484	test: 0.8731441	best: 0.7575621 (1)	total: 2.07s	remaining: 0us

bestTest = 0.7575620877
bestIteration = 1

Shrink model to first 2 iterations.
Learning rate set to 0.127482
0:	learn: 56846.8084490	test: 30535.4304594	best: 30535.4304594 (0)	total: 21ms	remaining: 2.08s
99:	learn: 12020.0902644	test: 38623.5320260	best: 30535.4304594 (0)	total: 2.84s	remaining: 0us

bestTest = 30535.43046
bestIteration = 0

Shrink model to first 1 iterations.
Learning rate set to 0.127482
0:	learn: 0.8838794	test: 0.7617019	best: 0.7617019 (0)	total: 14.8ms	remaining: 1.46s
99:	learn: 0.2950309	test: 1.0020890	best: 0.7617019 (0)	total: 2.3s	remaining: 0us

bestTest = 0.7617018542
bestIteration = 0

Shrink model to first 1 iterations.

### Severity metrics summary (new)
Квантили бьются по **`TARGET_SEV`** (true severity).
Сегменты: `VALUE_BEFORE_WITH` ≤ / > 50,000.

,variant,scope,transform,sample_weight,n,mae,bias,pred_sum,true_sum,sum_bias
0,raw,all_test,raw,none,29,"25,137.73","7,347.28","1,474,700.37","1,261,629.24","213,071.12"
1,log1p,all_test,log1p,none,29,"22,111.58","-9,793.64","977,613.56","1,261,629.24","-284,015.69"
2,weighted_sqrt,all_test,raw,sqrt,29,"30,670.33","11,096.22","1,583,419.72","1,261,629.24","321,790.47"
3,weighted_linear,all_test,raw,linear,29,"39,047.57","25,876.38","2,012,044.35","1,261,629.24","750,415.11"
4,raw_le50,VALUE_BEFORE_WITH<=50000,raw,none,13,"25,659.29","-2,539.03","626,170.56","659,177.93","-33,007.38"
5,log1p_le50,VALUE_BEFORE_WITH<=50000,log1p,none,13,"26,130.16","-17,597.20","430,414.28","659,177.93","-228,763.65"
6,raw_gt50,VALUE_BEFORE_WITH>50000,raw,none,16,"26,063.98","15,507.72","850,574.77","602,451.31","248,123.46"
7,log1p_gt50,VALUE_BEFORE_WITH>50000,log1p,none,16,"19,254.58","-2,868.80","556,550.47","602,451.31","-45,900.85"

### Severity quantile summary (все варианты)

,variant,bin_axis,scope,bin,n,true_sum,true_share,abs_err_sum,abs_err_share,mae,bias
0,raw,TARGET_SEV,all_test,"(6999.388, 33701.741]",15,"326,296.62",0.26,"429,606.38",0.59,"28,640.43","28,640.43"
1,raw,TARGET_SEV,all_test,"(33701.741, 90311.13]",11,"635,779.65",0.50,"156,330.78",0.21,"14,211.89","-6,679.84"
2,raw,TARGET_SEV,all_test,"(90311.13, 102714.47]",2,"194,920.91",0.15,"88,206.98",0.12,"44,103.49","-44,103.49"
3,raw,TARGET_SEV,all_test,"(102714.47, 104632.059]",1,"104,632.06",0.08,"54,849.99",0.08,"54,849.99","-54,849.99"
4,log1p,TARGET_SEV,all_test,"(6999.388, 33701.741]",15,"326,296.62",0.26,"178,610.07",0.28,"11,907.34","11,907.34"
5,log1p,TARGET_SEV,all_test,"(33701.741, 90311.13]",11,"635,779.65",0.50,"263,655.77",0.41,"23,968.71","-23,968.71"
6,log1p,TARGET_SEV,all_test,"(90311.13, 102714.47]",2,"194,920.91",0.15,"126,537.75",0.20,"63,268.87","-63,268.87"
7,log1p,TARGET_SEV,all_test,"(102714.47, 104632.059]",1,"104,632.06",0.08,"72,432.24",0.11,"72,432.24","-72,432.24"
8,weighted_sqrt,TARGET_SEV,all_test,"(6999.388, 33701.741]",15,"326,296.62",0.26,"504,217.89",0.57,"33,614.53","33,614.53"
9,weighted_sqrt,TARGET_SEV,all_test,"(33701.741, 90311.13]",11,"635,779.65",0.50,"218,283.32",0.25,"19,843.94","-1,408.08"
10,weighted_sqrt,TARGET_SEV,all_test,"(90311.13, 102714.47]",2,"194,920.91",0.15,"113,321.96",0.13,"56,660.98","-56,660.98"
11,weighted_sqrt,TARGET_SEV,all_test,"(102714.47, 104632.059]",1,"104,632.06",0.08,"53,616.53",0.06,"53,616.53","-53,616.53"
12,weighted_linear,TARGET_SEV,all_test,"(6999.388, 33701.741]",15,"326,296.62",0.26,"755,213.58",0.67,"50,347.57","50,347.57"
13,weighted_linear,TARGET_SEV,all_test,"(33701.741, 90311.13]",11,"635,779.65",0.50,"255,424.08",0.23,"23,220.37","10,631.23"
14,weighted_linear,TARGET_SEV,all_test,"(90311.13, 102714.47]",2,"194,920.91",0.15,"103,541.26",0.09,"51,770.63","-51,770.63"
15,weighted_linear,TARGET_SEV,all_test,"(102714.47, 104632.059]",1,"104,632.06",0.08,"18,200.74",0.02,"18,200.74","-18,200.74"
16,raw_le50,TARGET_SEV,VALUE_BEFORE_WITH<=50000,"(6999.388, 33701.741]",6,"143,364.65",0.22,"146,070.01",0.44,"24,345.00","24,345.00"
17,raw_le50,TARGET_SEV,VALUE_BEFORE_WITH<=50000,"(33701.741, 90311.13]",5,"313,397.70",0.48,"82,003.02",0.25,"16,400.60","-14,715.92"
18,raw_le50,TARGET_SEV,VALUE_BEFORE_WITH<=50000,"(90311.13, 102714.47]",1,"97,783.53",0.15,"48,976.73",0.15,"48,976.73","-48,976.73"
19,raw_le50,TARGET_SEV,VALUE_BEFORE_WITH<=50000,"(102714.47, 104632.059]",1,"104,632.06",0.16,"56,521.05",0.17,"56,521.05","-56,521.05"
20,log1p_le50,TARGET_SEV,VALUE_BEFORE_WITH<=50000,"(6999.388, 33701.741]",6,"143,364.65",0.22,"55,464.23",0.16,"9,244.04","9,244.04"
21,log1p_le50,TARGET_SEV,VALUE_BEFORE_WITH<=50000,"(33701.741, 90311.13]",5,"313,397.70",0.48,"148,570.13",0.44,"29,714.03","-29,714.03"
22,log1p_le50,TARGET_SEV,VALUE_BEFORE_WITH<=50000,"(90311.13, 102714.47]",1,"97,783.53",0.15,"63,682.29",0.19,"63,682.29","-63,682.29"
23,log1p_le50,TARGET_SEV,VALUE_BEFORE_WITH<=50000,"(102714.47, 104632.059]",1,"104,632.06",0.16,"71,975.46",0.21,"71,975.46","-71,975.46"
24,raw_gt50,TARGET_SEV,VALUE_BEFORE_WITH>50000,"(6999.388, 33701.741]",9,"182,931.97",0.30,"295,766.02",0.71,"32,862.89","32,862.89"
25,raw_gt50,TARGET_SEV,VALUE_BEFORE_WITH>50000,"(33701.741, 90311.13]",6,"322,381.95",0.54,"75,417.81",0.18,"12,569.64",-300.44
26,raw_gt50,TARGET_SEV,VALUE_BEFORE_WITH>50000,"(90311.13, 102714.47]",1,"97,137.38",0.16,"45,839.89",0.11,"45,839.89","-45,839.89"
27,log1p_gt50,TARGET_SEV,VALUE_BEFORE_WITH>50000,"(6999.388, 33701.741]",9,"182,931.97",0.30,"131,321.22",0.43,"14,591.25","14,539.02"
28,log1p_gt50,TARGET_SEV,VALUE_BEFORE_WITH>50000,"(33701.741, 90311.13]",6,"322,381.95",0.54,"114,878.86",0.37,"19,146.48","-19,146.48"
29,log1p_gt50,TARGET_SEV,VALUE_BEFORE_WITH>50000,"(90311.13, 102714.47]",1,"97,137.38",0.16,"61,873.14",0.20,"61,873.14","-61,873.14"

### Fin-effect summary (все варианты, один threshold)

,variant,scope,n,threshold,net_effect,model_effect,fact_effect
0,raw,all_test,120,0.80,0.00,"-1,325,240.58","-1,325,240.58"
1,log1p,all_test,120,0.80,0.00,"-1,325,240.58","-1,325,240.58"
2,weighted_sqrt,all_test,120,0.80,"94,193.36","-1,231,047.22","-1,325,240.58"
3,weighted_linear,all_test,120,0.80,"77,129.50","-1,248,111.08","-1,325,240.58"
4,raw_le50,VALUE_BEFORE_WITH<=50000,104,0.80,0.00,"-809,865.90","-809,865.90"
5,log1p_le50,VALUE_BEFORE_WITH<=50000,104,0.80,0.00,"-809,865.90","-809,865.90"
6,raw_gt50,VALUE_BEFORE_WITH>50000,16,0.80,0.00,"-515,374.68","-515,374.68"
7,log1p_gt50,VALUE_BEFORE_WITH>50000,16,0.80,0.00,"-515,374.68","-515,374.68"

### Fin-effect penalty summary (pred < fact)

,variant,scope,penalty_type,case,n,sum_base,sum_pred_sev,sum_true_sev,sum_fin_effect_model,sum_fin_effect_fact,delta_model_minus_fact,extra_under_sev_rub
0,raw,all_test,freq_miss,"pred=0, fact=1",27,"1,070,169.00","1,373,957.83","1,119,333.38","-1,070,169.00","-1,070,169.00",0.00,0.00
1,raw,all_test,freq_false_positive,"pred=1, fact=0",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,raw,all_test,sev_under,"pred=1, fact=1, pred_sev<true_sev",2,"255,071.58","100,742.54","142,295.87","-255,071.58","-255,071.58",0.00,"154,329.04"
3,raw,all_test,sev_over,"pred=1, fact=1, pred_sev≥true_sev",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,log1p,all_test,freq_miss,"pred=0, fact=1",27,"1,070,169.00","909,230.39","1,119,333.38","-1,070,169.00","-1,070,169.00",0.00,0.00
5,log1p,all_test,freq_false_positive,"pred=1, fact=0",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,log1p,all_test,sev_under,"pred=1, fact=1, pred_sev<true_sev",2,"255,071.58","68,383.17","142,295.87","-255,071.58","-255,071.58",0.00,"186,688.41"
7,log1p,all_test,sev_over,"pred=1, fact=1, pred_sev≥true_sev",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
8,weighted_sqrt,all_test,freq_miss,"pred=0, fact=1",27,"1,070,169.00","1,470,496.76","1,119,333.38","-1,070,169.00","-1,070,169.00",0.00,0.00
9,weighted_sqrt,all_test,freq_false_positive,"pred=1, fact=0",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10,weighted_sqrt,all_test,sev_under,"pred=1, fact=1, pred_sev<true_sev",1,"93,397.75","45,442.48","84,060.69","-93,397.75","-93,397.75",0.00,"47,955.27"
11,weighted_sqrt,all_test,sev_over,"pred=1, fact=1, pred_sev≥true_sev",1,"161,673.83","67,480.47","58,235.17","-67,480.47","-161,673.83","94,193.36",0.00
12,weighted_linear,all_test,freq_miss,"pred=0, fact=1",27,"1,070,169.00","1,875,847.29","1,119,333.38","-1,070,169.00","-1,070,169.00",0.00,0.00
13,weighted_linear,all_test,freq_false_positive,"pred=1, fact=0",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
14,weighted_linear,all_test,sev_under,"pred=1, fact=1, pred_sev<true_sev",1,"93,397.75","51,652.73","84,060.69","-93,397.75","-93,397.75",0.00,"41,745.02"
15,weighted_linear,all_test,sev_over,"pred=1, fact=1, pred_sev≥true_sev",1,"161,673.83","84,544.33","58,235.17","-84,544.33","-161,673.83","77,129.50",0.00
16,raw_le50,VALUE_BEFORE_WITH<=50000,freq_miss,"pred=0, fact=1",11,"554,794.32","527,311.04","516,882.07","-554,794.32","-554,794.32",0.00,0.00
17,raw_le50,VALUE_BEFORE_WITH<=50000,freq_false_positive,"pred=1, fact=0",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
18,raw_le50,VALUE_BEFORE_WITH<=50000,sev_under,"pred=1, fact=1, pred_sev<true_sev",2,"255,071.58","98,859.52","142,295.87","-255,071.58","-255,071.58",0.00,"156,212.06"
19,raw_le50,VALUE_BEFORE_WITH<=50000,sev_over,"pred=1, fact=1, pred_sev≥true_sev",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
20,log1p_le50,VALUE_BEFORE_WITH<=50000,freq_miss,"pred=0, fact=1",11,"554,794.32","362,211.81","516,882.07","-554,794.32","-554,794.32",0.00,0.00
21,log1p_le50,VALUE_BEFORE_WITH<=50000,freq_false_positive,"pred=1, fact=0",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
22,log1p_le50,VALUE_BEFORE_WITH<=50000,sev_under,"pred=1, fact=1, pred_sev<true_sev",2,"255,071.58","68,202.48","142,295.87","-255,071.58","-255,071.58",0.00,"186,869.10"
23,log1p_le50,VALUE_BEFORE_WITH<=50000,sev_over,"pred=1, fact=1, pred_sev≥true_sev",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
24,raw_gt50,VALUE_BEFORE_WITH>50000,freq_miss,"pred=0, fact=1",16,"515,374.68","850,574.77","602,451.31","-515,374.68","-515,374.68",0.00,0.00
25,raw_gt50,VALUE_BEFORE_WITH>50000,freq_false_positive,"pred=1, fact=0",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
26,raw_gt50,VALUE_BEFORE_WITH>50000,sev_under,"pred=1, fact=1, pred_sev<true_sev",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
27,raw_gt50,VALUE_BEFORE_WITH>50000,sev_over,"pred=1, fact=1, pred_sev≥true_sev",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
28,log1p_gt50,VALUE_BEFORE_WITH>50000,freq_miss,"pred=0, fact=1",16,"515,374.68","556,550.47","602,451.31","-515,374.68","-515,374.68",0.00,0.00
29,log1p_gt50,VALUE_BEFORE_WITH>50000,freq_false_positive,"pred=1, fact=0",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
30,log1p_gt50,VALUE_BEFORE_WITH>50000,sev_under,"pred=1, fact=1, pred_sev<true_sev",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
31,log1p_gt50,VALUE_BEFORE_WITH>50000,sev_over,"pred=1, fact=1, pred_sev≥true_sev",0,0.00,0.00,0.00,0.00,0.00,0.00,0.00

Severity zoo export: C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\data\processed\fin_effect
Допустимые SEVERITY_VARIANT: ('raw', 'log1p', 'weighted_sqrt', 'weighted_linear', 'raw_le50', 'log1p_le50', 'raw_gt50', 'log1p_gt50')
Сейчас SEVERITY_VARIANT = raw

## База факта и взносы

Три базы: **legacy** (ПСР), **new** (`TARGET_FREQ_AMOUNT` = claims+pret), **new_claims** (`TARGET_FREQ_CLAIMS_AMOUNT`, без претензий).
Взносы считаются отдельно под каждую базу (триггер ФУ только при base > 0).

In [14]:
from IPython.display import Markdown, display

from querulus.fin_effect import (
    compare_fact_bases,
    compare_premiums,
    compare_severity_targets,
)

pd.options.display.float_format = "{:,.2f}".format

print("=== Severity facts: TARGET_3_SEV vs TARGET_SEV ===")
sev_fact = compare_severity_targets(df)
display(sev_fact)
top = sev_fact.attrs.get("top_mismatches")
if top is not None and not top.empty:
    display(Markdown("Топ расхождений severity (факт)"))
    display(top)

print("=== Severity facts: TARGET_SEV vs TARGET_SEV_CLAIMS ===")
sev_claims = compare_severity_targets(df, legacy_col="TARGET_SEV", new_col="TARGET_SEV_CLAIMS")
display(sev_claims)

print("=== Денежная база: legacy / new / new_claims ===")
display(compare_fact_bases(df))

print("=== Взносы: отдельно для legacy / new / new_claims ===")
display(compare_premiums(df))

print("=== Fin-effect summary (повтор из обучения) ===")
display(triple.fin_effect_summary)

=== Severity facts: TARGET_3_SEV vs TARGET_SEV ===

                            metric        value
0                                n       400.00
1                 TARGET_3_SEV_sum 5,473,611.43
2                   TARGET_SEV_sum 5,511,374.20
3        sum_diff_new_minus_legacy    37,762.77
4           sum_diff_pct_vs_legacy         0.01
5                    exact_match_n       287.00
6                  exact_match_pct         0.72
7                       mismatch_n       113.00
8                             corr         1.00
9                              mae     1,020.43
10            mae_where_either_pos     3,612.14
11  median_abs_diff_where_mismatch     2,247.73

Топ расхождений severity (факт)

    INCIDENT_NUMBER  TARGET_3_SEV  TARGET_SEV  diff_new_minus_legacy  abs_diff
65       SYN-000065    178,981.74  207,893.71              28,911.97 28,911.97
8        SYN-000008    224,958.64  198,332.87             -26,625.77 26,625.77
261      SYN-000261    192,037.71  173,126.65             -18,911.06 18,911.06
53       SYN-000053    125,366.98  142,813.73              17,446.75 17,446.75
254      SYN-000254    125,498.94  136,929.64              11,430.69 11,430.69
194      SYN-000194    125,882.32  115,305.17             -10,577.15 10,577.15
272      SYN-000272     72,967.77   82,755.70               9,787.93  9,787.93
109      SYN-000109     80,069.64   71,124.10              -8,945.54  8,945.54
309      SYN-000309     95,690.14  104,632.06               8,941.92  8,941.92
318      SYN-000318     97,352.16   88,604.57              -8,747.60  8,747.60
140      SYN-000140     56,389.58   65,048.39               8,658.81  8,658.81
337      SYN-000337     75,812.51   84,060.69               8,248.19  8,248.19
216      SYN-000216     44,089.92   50,643.95               6,554.02  6,554.02
101      SYN-000101     44,109.98   50,490.86               6,380.88  6,380.88
163      SYN-000163     78,731.50   85,091.60               6,360.10  6,360.10
81       SYN-000081    108,144.50  101,787.34              -6,357.16  6,357.16
80       SYN-000080     48,205.86   42,225.80              -5,980.06  5,980.06
54       SYN-000054    322,984.82  317,086.14              -5,898.68  5,898.68
208      SYN-000208     39,044.26   44,867.51               5,823.25  5,823.25
221      SYN-000221     92,541.30   86,852.04              -5,689.26  5,689.26

=== Severity facts: TARGET_SEV vs TARGET_SEV_CLAIMS ===

                            metric         value
0                                n        400.00
1                   TARGET_SEV_sum  5,511,374.20
2            TARGET_SEV_CLAIMS_sum  3,906,876.98
3        sum_diff_new_minus_legacy -1,604,497.22
4           sum_diff_pct_vs_legacy         -0.29
5                    exact_match_n        287.00
6                  exact_match_pct          0.72
7                       mismatch_n        113.00
8                             corr          0.91
9                              mae      4,331.16
10            mae_where_either_pos     15,331.55
11  median_abs_diff_where_mismatch      6,926.04

=== Денежная база: legacy / new / new_claims ===

,side,part,sum,nonzero_n
0,legacy,Сумма_выплат_по_претензиям,"1,094,905.19",113
1,legacy,Сумма_взыскано_по_ФУ,"2,296,568.73",24
2,legacy,Суммы_взыскано_по_иску,"1,224,012.35",113
3,legacy,BASE (= pret+FU+court),"4,615,486.27",113
4,new,TARGET_FREQ_CLAIMS_AMOUNT,"2,750,169.92",84
5,new,TARGET_FREQ_PRET_AMOUNT,"1,929,410.68",113
6,new,BASE (= TARGET_FREQ_AMOUNT = claims+pret),"4,679,580.60",113
7,new_claims,"BASE (= TARGET_FREQ_CLAIMS_AMOUNT, без претензий)","2,750,169.92",84
8,diff,new_base - legacy_base,"64,094.33",113
9,diff,new_claims_base - new_base (= -pret),"-1,929,410.68",113

=== Взносы: отдельно для legacy / new / new_claims ===

,metric,value,note
0,fu_trigger_col,Сумма_взыскано_по_ФУ,общий boolean-триггер ФУ
1,fu_fee_amount,"100,000.00",
2,fu_trigger_n,24.00,Сумма_взыскано_по_ФУ > 0 (сырой)
3,fu_fee_n_legacy,24.00,триггер + legacy base > 0
4,fu_fee_n_new,24.00,триггер + TARGET_FREQ_AMOUNT > 0
5,fu_fee_n_new_claims,19.00,триггер + TARGET_FREQ_CLAIMS_AMOUNT > 0
6,premiums_sum_legacy,"2,400,000.00",
7,premiums_sum_new,"2,400,000.00",
8,premiums_sum_new_claims,"1,900,000.00",без претензий → меньше сиротских взносов
9,legacy_fact_with_premiums,"7,015,486.27",legacy fin_effect_fact
10,new_fact_with_premiums,"7,079,580.60",TARGET_FREQ_AMOUNT + взносы
11,new_claims_fact_with_premiums,"4,650,169.92",TARGET_FREQ_CLAIMS_AMOUNT + взносы

=== Fin-effect summary (повтор из обучения) ===

,stack,frequency_target,severity_target,fact_mode,fact_amount_column,best_threshold,fact_effect,model_effect,net_effect
0,legacy,TARGET_2,TARGET_3_SEV,legacy_psr,legacy_psr,0.90,"-1,185,919.58","-1,185,919.58",0.00
1,new,TARGET_FREQ,TARGET_SEV,icnl,TARGET_FREQ_AMOUNT,0.80,"-1,325,240.58","-1,325,240.58",0.00
2,new_claims,TARGET_FREQ_CLAIMS,TARGET_SEV_CLAIMS,icnl,TARGET_FREQ_CLAIMS_AMOUNT,0.95,"-763,137.83","-763,137.83",0.00

## B. Train-loop кандидата `new`

Порядок: FE → corr → PSI/L1 → SHAP → noise-cut → backward-elim → HPO → fit (`SEVERITY_VARIANT`) → cal.

`SEVERITY_VARIANT` задаётся во флагах (после zoo). Сегментные варианты переобучают severity на срезе `VALUE_BEFORE_*`.

In [15]:
# --- STAGE: B flags overview ---
from querulus.training import TrainLoopFlags, run_train_loop_new

print("[B] RUN_TRAIN_LOOP_NEW =", RUN_TRAIN_LOOP_NEW)
print("[B] RUN_FEATURE_SELECT =", RUN_FEATURE_SELECT, "n=", FEATURE_SELECT_N)
print("[B] RUN_NOISE_CUT =", RUN_NOISE_CUT)
print("[B] RUN_BACKWARD_ELIM =", RUN_BACKWARD_ELIM)
print("[B] RUN_FIT =", RUN_FIT)
print("[B] SEVERITY_VARIANT =", SEVERITY_VARIANT)
train_loop_flags = TrainLoopFlags(
    use_fe_features=USE_FE_FEATURES,
    run_corr_filter=RUN_CORR_FILTER,
    corr_filter_threshold=CORR_FILTER_THRESHOLD,
    run_psi_filter=RUN_PSI_FILTER,
    psi_threshold=PSI_THRESHOLD,
    l1_threshold=L1_THRESHOLD,
    run_shap_select=RUN_FEATURE_SELECT,
    shap_n_features=FEATURE_SELECT_N,
    run_noise_cut=RUN_NOISE_CUT,
    run_backward_elim=RUN_BACKWARD_ELIM,
    run_fit=RUN_FIT,
    run_hpo=RUN_HPO,
    run_calibration=RUN_CALIBRATION,
    hpo_n_trials=HPO_N_TRIALS,
    use_mlflow=True,
    severity_variant=SEVERITY_VARIANT,
    severity_value_column="VALUE_BEFORE_WITH",
    severity_value_threshold=SEVERITY_SEGMENT_RUB,
)
from querulus.training.train_loop import print_flags_table
print_flags_table(train_loop_flags)

[B] RUN_TRAIN_LOOP_NEW = True
[B] RUN_FEATURE_SELECT = True n= 5
[B] RUN_NOISE_CUT = False
[B] RUN_BACKWARD_ELIM = False
[B] RUN_FIT = False
[B] SEVERITY_VARIANT = raw
[B] === Train-loop flags ===
[B]   ON   USE_FE_FEATURES    — derived/incident FE_* в пуле
[B]   OFF  RUN_CORR_FILTER    — Pearson-filter числовых, раздельно freq/sev
[B]   OFF  RUN_PSI_FILTER     — PSI>0.5 / L1>0.5 (train vs Val)
[B]   ON   RUN_FEATURE_SELECT — SHAP RecursiveByShapValues → 5
[B]   OFF  RUN_NOISE_CUT      — после FS: отсев фич слабее FE_NOISE_UNIFORM
[B]   OFF  RUN_BACKWARD_ELIM  — после noise-cut: срез с конца, best PR-AUC / MAE
[B]   OFF  RUN_FIT            — финальный fit (+ HPO/cal если включены)
[B]   OFF  RUN_HPO            — Optuna+MLflow (только при RUN_FIT)
[B]   OFF  RUN_CALIBRATION    — калибровка freq на Cal
[B]   ON   SEVERITY_VARIANT   — raw

### B1. Запуск train-loop

При `RUN_TRAIN_LOOP_NEW=False` ячейка только печатает SKIPPED.
Артефакты: `data/processed/train_loop_new/` (corr JSON, HPO params, feature selection). PSI-filter JSON не пишет — список dropped в логе и в `train_loop_result.psi_dropped`.

In [16]:
# --- STAGE: train_loop_new ---
# Итоги (фичи / HPO / fin-effect / plots) — в секции C ниже.
from querulus.training.config import TrainingConfig

train_loop_result = None
loop_cfg = None
if not RUN_TRAIN_LOOP_NEW:
    print("[B] >>> STAGE train_loop_new SKIPPED (RUN_TRAIN_LOOP_NEW=False)")
else:
    print("[B] >>> STAGE train_loop_new START")
    # Конфиг как у VIEW_STACK=new, но сплит Val/Cal внутри train
    loop_cfg = TrainingConfig(
        features_source=FEATURES_SOURCE,
        frequency_select_features=False,  # управляется RUN_FEATURE_SELECT внутри loop
        severity_select_features=False,
        frequency_target="TARGET_FREQ",
        severity_target="TARGET_SEV",
        use_fe_features=USE_FE_FEATURES,
    )
    train_loop_result = run_train_loop_new(
        df, loop_cfg, train_loop_flags
    )
    print("[B] >>> STAGE train_loop_new DONE")
    print(
        "[B] ECE before/after:",
        train_loop_result.ece_before,
        train_loop_result.ece_after,
    )
    print("[B] PSI dropped:", train_loop_result.psi_dropped)
    print(
        "[B] sizes: train=%d val=%d cal=%d test=%d"
        % (
            len(train_loop_result.splits.train),
            len(train_loop_result.splits.val),
            len(train_loop_result.splits.cal),
            len(train_loop_result.splits.test),
        )
    )

100%|██████████| 38/38 [00:00<00:00, 3166.52it/s]

[B] >>> STAGE train_loop_new START
[B] === Train-loop flags ===
[B]   ON   USE_FE_FEATURES    — derived/incident FE_* в пуле
[B]   OFF  RUN_CORR_FILTER    — Pearson-filter числовых, раздельно freq/sev
[B]   OFF  RUN_PSI_FILTER     — PSI>0.5 / L1>0.5 (train vs Val)
[B]   ON   RUN_FEATURE_SELECT — SHAP RecursiveByShapValues → 5
[B]   OFF  RUN_NOISE_CUT      — после FS: отсев фич слабее FE_NOISE_UNIFORM
[B]   OFF  RUN_BACKWARD_ELIM  — после noise-cut: срез с конца, best PR-AUC / MAE
[B]   OFF  RUN_FIT            — финальный fit (+ HPO/cal если включены)
[B]   OFF  RUN_HPO            — Optuna+MLflow (только при RUN_FIT)
[B]   OFF  RUN_CALIBRATION    — калибровка freq на Cal
[B]   ON   SEVERITY_VARIANT   — raw
[B] severity_variant=raw (transform=raw, weight=none, segment=all)
[B] splits: train=245 val=22 cal=13 test=120 (train_core=('2022-01-01', '2024-01-02'), val=('2024-01-03', '2024-04-01'), cal=('2024-04-02', '2024-05-31'), test=('2024-06-01', '2025-06-01'))
[B] >>> STAGE use_fe_features ON (FE_* allowed in pools)
[B] mvp pools (value_type): freq=10 sev=4 cats=5
[B] >>> STAGE corr_filter SKIPPED (RUN_CORR_FILTER=False)
[B] >>> STAGE psi_filter SKIPPED (RUN_PSI_FILTER=False)
[B] >>> STAGE feature_select START — n=5; eval=val

100%|██████████| 38/38 [00:00<00:00, 3167.02it/s]

Learning rate set to 0.034303
0:	learn: 0.6927666	test: 0.6917326	best: 0.6917326 (0)	total: 9.91ms	remaining: 3.71s

250:	learn: 0.2651864	test: 0.5960917	best: 0.5938685 (246)	total: 5.69s	remaining: 2.81s
374:	learn: 0.1543848	test: 0.6148802	best: 0.5811729 (295)	total: 8.69s	remaining: 0us

bestTest = 0.5811729334
bestIteration = 295

Shrink model to first 296 iterations.
Learning rate set to 0.138128
0:	learn: 53739.4631588	test: 38768.3150987	best: 38768.3150987 (0)	total: 7.95ms	remaining: 787ms
99:	learn: 21044.0050359	test: 36893.7218639	best: 36362.9242033 (87)	total: 2.05s	remaining: 0us

bestTest = 36362.9242
bestIteration = 87

Shrink model to first 88 iterations.

C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\gini.py:54: FutureWarning:

The provided callable <function mean at 0x000001D52DD12200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\gini.py:54: FutureWarning:

The provided callable <function mean at 0x000001D52DD12200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\grchi\Desktop\pet_projects\outboxml\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\gini.py:54: FutureWarning:

The provided callable <function mean at 0x000001D52DD12200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

C:\Users\grchi\Desktop\pet_projects\modeldiagnostics\src\gini.py:54: FutureWarning:

The provided callable <function mean at 0x000001D52DD12200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

[B] >>> STAGE feature_select DONE → freq=10 sev=4
[B] >>> STAGE noise_cut SKIPPED (RUN_NOISE_CUT / пустой пул=False)
[B] >>> STAGE backward_elim SKIPPED (RUN_BACKWARD_ELIM / пустой пул=False)
[B] feature select artifacts → C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\data\processed\train_loop_new
[B] feature select report → C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\data\processed\train_loop_new\new_selected_features_report_latest.html
[B] >>> STAGE hpo SKIPPED (RUN_FIT=False=False)
[B] >>> STAGE fit_new SKIPPED (RUN_FIT=False=False)
[B] >>> STAGE calibration SKIPPED (RUN_FIT=False=False)
[B] artifacts → C:\Users\grchi\Desktop\pet_projects\outboxml\examples\querulus\data\processed\train_loop_new (feature select only)
[B] >>> STAGE train_loop_new DONE
[B] ECE before/after: None None
[B] PSI dropped: []
[B] sizes: train=245 val=22 cal=13 test=120

## C. Итоги кандидата B

При `RUN_FIT=False` — только отобранные фичи (C1). HPO / финэффект / plots — при `RUN_FIT=True`.
Списки также в `data/processed/train_loop_new/`.

**Сплиты:** train_core / Val / Cal / holdout Test. `frequency_split.x_test` в B = Val.

In [17]:
# --- STAGE: C1 features + importance ---
from IPython.display import Markdown, display
from querulus.training.pipeline import format_features_table

if train_loop_result is None:
    print("[C] >>> STAGE features SKIPPED (нет train_loop_result)")
else:
    if not RUN_FIT:
        print("[C] RUN_FIT=False — показ отобранных фич (C2–C4 пропущены)")
    tr = train_loop_result.training
    splits = train_loop_result.splits
    display(Markdown("### [C] Сплиты блока B"))
    display(
        pd.DataFrame(
            [
                {"role": "train_core", "n": len(splits.train)},
                {"role": "val", "n": len(splits.val)},
                {"role": "cal", "n": len(splits.cal)},
                {"role": "test (holdout)", "n": len(splits.test)},
            ]
        )
    )
    print(
        "[C] B обучена на train_core (меньше полного train A); "
        "итоговый финэффект — на том же Test."
    )

    display(Markdown("### [C] Frequency features"))
    display(
        format_features_table(
            train_loop_result.frequency_features,
            tr.frequency_categorical_features,
        )
    )
    display(Markdown("### [C] Severity features"))
    display(
        format_features_table(
            train_loop_result.severity_features,
            tr.severity_categorical_features,
        )
    )
    display(Markdown("### [C] Frequency importance (top)"))
    display(tr.frequency_importance.head(30))
    display(Markdown("### [C] Severity importance (top)"))
    display(tr.severity_importance.head(30))

[C] RUN_FIT=False — показ отобранных фич (C2–C4 пропущены)

### [C] Сплиты блока B

             role    n
0      train_core  245
1             val   22
2             cal   13
3  test (holdout)  120

[C] B обучена на train_core (меньше полного train A); итоговый финэффект — на том же Test.

### [C] Frequency features

                       feature         type
0  EVENT_CREATED_BY_GIBDD_FLAG  categorical
1                       FILIAL  categorical
2      VICTIM_VEHICLE_CATEGORY  categorical
3               APPLICANT_FORM  categorical
4               RECIEVE_METHOD  categorical
5           VICTIM_VEHICLE_AGE      numeric
6            VICTIM_MAX_WEIGHT      numeric
7       GUILTY_CAPACITY_ENGINE      numeric
8                APPLICANT_AGE      numeric
9                   EVENT_YEAR      numeric

### [C] Severity features

                             feature         type
0                     LOSS_UNIT_ZONE  categorical
1             VICTIM_VEHICLE_COUNTRY  categorical
2                        APPLY_DELAY      numeric
3  FE_VALUE_BEFORE_WITHOUT_REAL_2020      numeric

### [C] Frequency importance (top)

                       feature  importance
0                       FILIAL       14.94
1               RECIEVE_METHOD       14.16
2            VICTIM_MAX_WEIGHT       12.11
3       GUILTY_CAPACITY_ENGINE       11.84
4                APPLICANT_AGE       11.47
5               APPLICANT_FORM       10.42
6      VICTIM_VEHICLE_CATEGORY       10.15
7           VICTIM_VEHICLE_AGE        8.62
8  EVENT_CREATED_BY_GIBDD_FLAG        4.06
9                   EVENT_YEAR        2.23

### [C] Severity importance (top)

                             feature  importance
0                        APPLY_DELAY       38.82
1  FE_VALUE_BEFORE_WITHOUT_REAL_2020       21.80
2                     LOSS_UNIT_ZONE       20.64
3             VICTIM_VEHICLE_COUNTRY       18.75

In [18]:
# --- STAGE: C2 HPO best params ---
import json

if train_loop_result is None or not RUN_FIT:
    print("[C] >>> STAGE HPO SKIPPED (нет train_loop_result или RUN_FIT=False)")
else:
    display(Markdown("### [C] HPO best params"))

    def _show_hpo(label, hpo, fallback_key):
        if hpo is not None:
            print(
                f"{label}: best_{hpo.optimize_metric}={hpo.best_value:.4f} "
                f"(n_trials={hpo.n_trials}, direction={hpo.direction})"
            )
            display(pd.Series(hpo.best_params, name=label).to_frame("value"))
            return
        art = train_loop_result.artifacts_dir
        path = (art / "hpo_best_params_new.json") if art else None
        if path is not None and path.exists():
            payload = json.loads(path.read_text(encoding="utf-8"))
            params = payload.get(fallback_key) or {}
            print(f"{label}: из {path.name} (объект HpoResult пуст)")
            display(pd.Series(params, name=label).to_frame("value"))
        else:
            print(f"{label}: HPO выключен / нет best_params — defaults CatBoost")

    _show_hpo("frequency", train_loop_result.frequency_hpo, "frequency")
    _show_hpo("severity", train_loop_result.severity_hpo, "severity")

[C] >>> STAGE HPO SKIPPED (нет train_loop_result или RUN_FIT=False)

In [19]:
# --- STAGE: C3 fin-effect: threshold on Val → report on Test ---
from querulus.fin_effect import (
    create_summary_table,
    export_analytics_excel,
    export_summary_excel,
    print_best_threshold_report,
    resolve_fin_effect_config,
    run_fin_effect_from_training,
)

fin_effect_b = None
FIN_EFFECT_CONFIG_B = None

if train_loop_result is None or not RUN_FIT:
    print("[C] >>> STAGE fin_effect SKIPPED (нет train_loop_result или RUN_FIT=False)")
else:
    tr = train_loop_result.training
    splits = train_loop_result.splits
    FIN_EFFECT_CONFIG_B = resolve_fin_effect_config(
        df,
        frequency_target="TARGET_FREQ",
        severity_target="TARGET_SEV",
        loaded_from_checkpoint=(DATA_SOURCE != "pipeline"),
        legacy_dataset=LOAD_LEGACY_DATASET,
    )

    # Порог на Val (не holdout)
    fe_val = run_fin_effect_from_training(
        df,
        tr,
        effect_index=splits.val,
        frequency_target_column="TARGET_FREQ",
        config=FIN_EFFECT_CONFIG_B,
    )
    thr_b = float(fe_val.best_threshold)
    print(f"[C] threshold from Val = {thr_b:.4f} (n_val={len(splits.val)})")

    # Итог на holdout Test
    fin_effect_b = run_fin_effect_from_training(
        df,
        tr,
        effect_index=splits.test,
        frequency_target_column="TARGET_FREQ",
        threshold=thr_b,
        config=FIN_EFFECT_CONFIG_B,
    )
    display(Markdown("### [C] Fin-effect на holdout Test (порог с Val)"))
    print_best_threshold_report(fin_effect_b)

    summary_b = create_summary_table(fin_effect_b.frame, FIN_EFFECT_CONFIG_B)
    display(summary_b.style.format("{:,.0f}", subset=summary_b.columns[3:]))

    FIN_EFFECT_DIR = PROJECT_ROOT / "data" / "processed" / "fin_effect"
    FIN_EFFECT_DIR.mkdir(parents=True, exist_ok=True)
    export_summary_excel(summary_b, FIN_EFFECT_DIR / "summary_table_train_loop_new.xlsx")
    export_analytics_excel(
        fin_effect_b.frame,
        FIN_EFFECT_DIR / "Аналитика_train_loop_new.xlsx",
        config=FIN_EFFECT_CONFIG_B,
    )

    # Сравнение с A(new) на том же Test — A в плюсе по объёму обучения
    rows = [
        {
            "model": "B (train_core→Test)",
            "threshold": thr_b,
            "fact": fin_effect_b.fact_effect_total,
            "model_effect": fin_effect_b.model_effect_total,
            "net": fin_effect_b.net_effect,
            "n": len(splits.test),
        }
    ]
    _triple = globals().get("triple")
    if (
        _triple is not None
        and getattr(_triple, "fin_effects", None)
        and "new" in _triple.fin_effects
    ):
        fe_a = _triple.fin_effects["new"]
        rows.append(
            {
                "model": "A new (full train→Test)",
                "threshold": fe_a.best_threshold,
                "fact": fe_a.fact_effect_total,
                "model_effect": fe_a.model_effect_total,
                "net": fe_a.net_effect,
                "n": len(fe_a.frame),
            }
        )
        print(
            "[C] A vs B: оба на календарном Test; у B короче train (val/cal вырезаны). "
            "Порог A подобран на Test, у B — на Val."
        )
    display(Markdown("### [C] A vs B (сравнение с оговорками)"))
    display(pd.DataFrame(rows))

[C] >>> STAGE fin_effect SKIPPED (нет train_loop_result или RUN_FIT=False)

In [20]:
# --- STAGE: C4 plots (diagnostics on Val; fin-effect plots on Test) ---
from querulus.fin_effect import (
    plot_confusion_matrix,
    plot_cost_confusion_heatmaps,
    plot_positive_cases_by_month,
    plot_precision_recall_vs_threshold,
    plot_severity_fact_vs_pred_binned,
    plot_target_monthly_share,
)
from querulus.training.plots import run_model_diagnostics_visualizations

if train_loop_result is None or fin_effect_b is None or FIN_EFFECT_CONFIG_B is None:
    print("[C] >>> STAGE plots SKIPPED (нет результата или RUN_FIT=False)")
else:
    tr = train_loop_result.training
    splits = train_loop_result.splits
    display(
        Markdown(
            "### [C] Diagnostics (train_core vs Val)\n\n"
            "Val = early-stop / SHAP eval, **не** holdout Test."
        )
    )
    run_model_diagnostics_visualizations(
        df, tr, loop_cfg or TrainingConfig(frequency_target="TARGET_FREQ", severity_target="TARGET_SEV")
    )

    display(Markdown("### [C] Fin-effect plots (holdout Test)"))
    frame = fin_effect_b.frame
    y_test = frame[FIN_EFFECT_CONFIG_B.frequency_target_column]
    # Признаки для PR-кривой — строки Test из df (не frequency_split.x_test = Val)
    x_test = df.loc[frame.index, tr.frequency_features].copy()
    for col in tr.frequency_categorical_features:
        if col in x_test.columns:
            x_test[col] = x_test[col].astype(str)

    thr = fin_effect_b.best_threshold
    plot_confusion_matrix(
        y_test,
        frame["pred_freq"],
        title=f"Confusion Matrix TARGET_FREQ (B Test, thr={thr:.2f})",
    )
    plot_precision_recall_vs_threshold(tr.frequency_model, x_test, y_test)
    plot_cost_confusion_heatmaps(frame, y_test, frame["pred_freq"])
    plot_severity_fact_vs_pred_binned(
        frame,
        frame["TARGET_SEV"] if "TARGET_SEV" in frame.columns else frame[FIN_EFFECT_CONFIG_B.severity_target_column],
        frame["pred_sev"],
        mask_actual_claim=(y_test == 1),
        config=FIN_EFFECT_CONFIG_B,
    )
    plot_target_monthly_share(df, config=FIN_EFFECT_CONFIG_B)
    plot_positive_cases_by_month(df, config=FIN_EFFECT_CONFIG_B)

[C] >>> STAGE plots SKIPPED (нет результата или RUN_FIT=False)